ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.injent.AppKt.configureApp
gigachat:
  authkey: "${GIGACHAT_AUTH_KEY}"
  system-instructions-file: system_instructions.txt
  max-retries: 2
  model: GigaChat-Pro
compassapi:
  host: "${COMPASS_API_HOST}"
  apikey: "${COMPASS_API_KEY}"
access:
  - role: "SUPERUSER"
    login: "admin"
    password: "${ADMIN_PASSWORD}"
  - role: "USER"
    login: "otdel"
    password: "${USER_PASSWORD}"
