services:
  fastapi:
    build: .
    env_file: .env
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql+asyncpg://postgres:password@postgres:5432/compass-api
    ports:
      - "${API_EX_PORT:-8880}:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: compass-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  compassadmin:
    image: ghcr.io/injent/compass-admin:latest
    container_name: compassadmin
    env_file: .env.compass-admin
    environment:
      COMPASS_DB_PATH: /app/data/compassadmin.db
      GOOGLE_CREDENTIALS_PATH: /app/google/credentials.json
      GOOGLE_TOKENS_DIR: /app/tokens
    ports:
      - "${VALIDATOR_EX_PORT:-8881}:8080"
    volumes:
      - ./compass-admin-config/application.yaml:/app/config/application.yaml:ro
      - ./compass-admin-config/google:/app/google
      - ./compass-admin-config/tokens:/app/tokens
      - ./compass-admin-config/data:/app/data
    restart: unless-stopped

volumes:
  pgdata:
