# SSL termination expected at reverse proxy / Cloudflare / external LB
# To add certbot: https://nginx.org/en/docs/http/configuring_https_servers.html

upstream fastapi_backend {
    server fastapi:8000 fail_timeout=0;
}

server {
    listen 80;
    server_name bgitu-compass.ru;

    keepalive_timeout 5;
    client_max_body_size 4G;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/index.html =404;
    }

    location /ios-instructions {
        alias /usr/share/nginx/html/ios-instructions;
        autoindex on;
    }

    location /download {
        alias /data/updates/bgitu_compass.apk;
        add_header Content-Disposition "attachment; filename=bgitu_compass.apk";
        autoindex off;
    }

    location = /robots.txt {
        alias /usr/share/nginx/html/robots.txt;
        access_log off;
        log_not_found off;
    }

    location /contacts/kirillPudov/vk {
        return 301 https://vk.com/koespe;
    }
    location /contacts/kirillPudov/tg {
        return 301 https://t.me/koespe;
    }
    location /contacts/eliseyVerevkin/vk {
        return 301 https://vk.com/injent;
    }
    location /contacts/eliseyVerevkin/tg {
        return 301 https://t.me/Injent;
    }
    location /contacts/kirillPudov/avatar.png {
        alias /usr/share/nginx/html/kirill.png;
    }
    location /contacts/eliseyVerevkin/avatar.png {
        alias /usr/share/nginx/html/elisey.png;
    }
}

server {
    listen 80;
    server_name api-ssl.bgitu-compass.ru;

    keepalive_timeout 5;
    client_max_body_size 4G;
    proxy_read_timeout 600;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://fastapi_backend;
    }
}
