#!/bin/bash

NAME=bgitu-api
DIR=/home/user1/bgitu_api
USER=root
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/venv/bin/activate
BIND=unix:$DIR/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV

exec gunicorn app:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
