[supervisord]
environment=BASE_DIR="/home/user1/compass"

[program:compass-api]
command=bash %(ENV_BASE_DIR)s/api/start_gunicorn
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=%(ENV_BASE_DIR)s/api/logs/gunicorn_logs.log
