[supervisord]
environment=BASE_DIR="/home/koespe/compass"

[program:compass-api]
command=bash %(ENV_BASE_DIR)s/api/start_gunicorn
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=%(ENV_BASE_DIR)s/api/logs/gunicorn_logs.log

[program:compass-site-updates]
command=%(ENV_BASE_DIR)s/api/venv/bin/python3 modules/site_updates.py
directory=%(ENV_BASE_DIR)s
environment=PYTHONPATH=%(ENV_BASE_DIR)s
autostart=true
autorestart=true
redirect_stdout=true
redirect_stderr=true

[program:compass-termStartDate-variable-updates]
command=%(ENV_BASE_DIR)s/api/venv/bin/python3 modules/term_start_date_scraper.py
directory=%(ENV_BASE_DIR)s
environment=PYTHONPATH=%(ENV_BASE_DIR)s
user=root
autostart=true
autorestart=true
redirect_stdout=true
redirect_stderr=true