[program:compass-api]
command=bash /home/BotsCouch/bgitu_api/start_gunicorn
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/BotsCouch/bgitu_api/logs/gunicorn_logs.log

[program:bgitu-updates]
command=/home/BotsCouch/bgitu_api/venv/bin/python3 /home/BotsCouch/bgitu_api/modules/site_updates.py
directory=/home/BotsCouch/bgitu_api/
autostart=true
autorestart=true
redirect_stdout=true
redirect_stderr=true